### ISSUE TITLE
OutOfMemoryError in testNoReadsInFirstSplitBug unit test

### ISSUE THREAD

**Issue by heuermh** [HadoopGenomics/Hadoop-BAM#101]
The testNoReadsInFirstSplitBug unit test fails for me on my lesser laptop with OutOfMemoryError

```bash
$ mvn test
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.seqdoop.hadoop_bam.TestBAMInputFormat
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.126 sec <<< FAILURE! - in org.seqdoop.hadoop_bam.TestBAMInputFormat
testNoReadsInFirstSplitBug(org.seqdoop.hadoop_bam.TestBAMInputFormat)  Time elapsed: 1.086 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at htsjdk.samtools.SAMFileHeader.addComment(SAMFileHeader.java:292)
	at org.seqdoop.hadoop_bam.TestBAMInputFormat.writeBamFileWithLargeHeader(TestBAMInputFormat.java:102)
	at org.seqdoop.hadoop_bam.TestBAMInputFormat.testNoReadsInFirstSplitBug(TestBAMInputFormat.java:127)
...
Results :

Tests in error: 
  TestBAMInputFormat.testNoReadsInFirstSplitBug:127->writeBamFileWithLargeHeader:102 » OutOfMemory

Tests run: 150, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by heuermh** [comment]
Fixed by setting `MAVEN_OPTS` to anything reasonable.
