### ISSUE TITLE
Should codepaths that use java.nio catch ProviderNotFoundException?

### ISSUE THREAD

**Issue by fnothaft** [HadoopGenomics/Hadoop-BAM#125]
I was running on a non-HDFS file system that did not have a registered `java.nio.file.spi.FileSystemProvider` for the FS scheme. I was loading the whole file, so I didn't _need_ the index, but was getting a `ProviderNotFoundException` when [loading the index when picking splits](https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/BAMInputFormat.java#L172). Turns out, the BAM split picking code [only catches an IOError](https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/BAMInputFormat.java#L152-L156) when using the BAM index. I think the correct behavior would be to also catch the `java.nio.file.ProviderNotFoundException` exception as well. Thoughts?

**Comment by tomwhite** [comment]
@fnothaft Yes, it should do.

**Comment by fnothaft** [comment]
Thanks @tomwhite! I've opened #130 to catch this in the BAM split picking code. It looks like it will still get thrown from the BAM RecordReader. From a cursory glance, neither the CRAM nor VCF code use it to load java.nio to load indices. Is there anywhere else? Loading the CRAM reference, perhaps?

**Comment by cmnbroad** [comment]
@fnothaft For the CRAM reference, I'm not sure we could do anything to handle it other then re-throw anyway since the ref is required.

**Comment by fnothaft** [comment]
Yeah, agreed. TBH, there may be a similar problem in the BAMRecordReader codepath, because I think the BAMRecordReader needs the java.nio provider to initialize the record reader, even if the user hasn't defined specific intervals to load. That said, I haven't tested this, so I'm not 100% sure.

**Comment by a1xt06** [comment]
I think I can confirm what @fnothaft said in the last post about BAMRecordReader. This error is thrown after trying to load the entire bam file on s3. Let me know if you want to full stack trace.
```
Caused by: java.nio.file.ProviderNotFoundException: Provider "s3a" not found
  at java.nio.file.FileSystems.newFileSystem(FileSystems.java:341)
  at org.seqdoop.hadoop_bam.util.NIOFileUtil.asPath(NIOFileUtil.java:40)
  at org.seqdoop.hadoop_bam.BAMRecordReader.initialize(BAMRecordReader.java:140)
  at org.seqdoop.hadoop_bam.BAMInputFormat.createRecordReader(BAMInputFormat.java:121)
  at org.seqdoop.hadoop_bam.AnySAMInputFormat.createRecordReader(AnySAMInputFormat.java:190)
  at org.apache.spark.rdd.NewHadoopRDD$$anon$1.liftedTree1$1(NewHadoopRDD.scala:178)
  at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:177)
  at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:134)
  at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
  at org.apache.spark.scheduler.Task.run(Task.scala:99)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
```
